### ISSUE TITLE
Document capybara default wait time, or make it configurable

### ISSUE THREAD

**Issue by tigris** [jhchabran/photograph#11]
I was wondering why as soon as I turned on the usage of this gem, my specs went from 8 seconds to 97 just by requiring the gem, not even using it yet. Took me a few hours to discover that it's because line 4 of artist.rb is blatantly setting the capybara default wait time to 15 seconds.

Capybara has a .using_wait_time() method that takes a block, 1 solution could be to have a Photograph.default_wait_time or similar and wrap any capybara calls in this gem using the above block. But that constant name would probably get confused with the wait_time option you can pass to Artist.new.

For now I've wrapped my own capybara usage with the using_wait_time(0.1) block since I am just doing simple has_selector?() checks, and waiting 15 seconds to find out said selector doesn't exist is pretty annoying.

**Comment by jhchabran** [comment]
Oh shit, since this is global, it propagated through your whole test suite.

Since you're the one mostly using this gem, as I don't anymore, I highly suggest you take over maintaining it, I'd gladly help when I got time. 

Meanwhile, the capybara block is clearly the right way to handle it. I'll add that asap. 

Sorry for your wasted time :/

**Comment by jhchabran** [comment]
Ok, it's fixed, I'll add some configuration for that and lower the default wait time.

**Comment by jhchabran** [comment]
Made configurable by using 

``` ruby
Photograph::Artist.new(:url => URL, :capybara_wait_time => 4)
```
